Gerenciador:

    Tela:

<Player>:
    source: 'imagens/mario.png'
    size_hint:None,None
    size: 128,128
    x:0
    y:0
    
<Bloco>:
    px:0
    py:0
    source: 'imagens/bloco.png'
    size_hint:None,None
    size: 32,32
    x:32*root.px
    y:32*root.py
<Tela>:
    canvas:
        Color:
            rgba:1,1,1,1
        Rectangle:
            size:820,600
            pos:self.pos
            source:'imagens/fundo.png'