Gerenciador:

    Tela:

<Player>:
    source: 'imagens/mario.png'
    size_hint:None,None
    size: 512,512
    x:10
    y:10
    
<Bloco>:
    px:0
    py:0
    source: 'imagens/bloco.png'
    size_hint:None,None
    size: 112,112
    x:112*root.px
    y:112*root.py
<Tela>:
    canvas:
        Color:
            rgba:1,1,1,1
        Rectangle:
            size:820,640
            pos:self.pos
            source:'imagens/fundo.png'